### ISSUE TITLE
Emoji keyboard closed automatically 

### ISSUE THREAD

**Issue by alberto-salieto-scopely** [support-fennecx/advancedinputfield2#22]
**Describe the bug**
On Android, when pressing the emoji keyboard button, it appears and when the animation has finished, it closes and come back to the normal keyboard. Probably is caused from some race career, and maybe related with https://github.com/support-fennecx/advancedinputfield2/issues/20

**To Reproduce**
1. Select an AdvancedInputField
2. Try to add an emoji from the keyboard
3. Emoji keyboard is automatically minimized

**Expected behavior**
It should keep opened the emoji keyboard

**Screenshots**
![image](https://user-images.githubusercontent.com/75724417/111345247-5fba2200-867d-11eb-9f05-f4560a8880c0.png)

**Environment**
 - OS: Android
 - Version of the plugin 2.0.5

**Comment by support-fennecx** [comment]
@alberto-salieto-scopely 
Tried to reproduce it by installing the sample scene "TextMeshPro/Chat" on different Android devices.
Using the default/stock keyboard of those devices I could input different emojis.
Also, tried to use SwiftKey keyboard on one of those devices and that one also seems to work.

Maybe it's a device specific issue. Can you use the emoji keyboard normally in other apps on that device?
I couldn't really see in your screenshot which device and which keyboard you are using. I guessed Swiftkey, but I'm not sure.
So could you also mention the device and keyboard you are using?

**Comment by alberto-salieto-scopely** [comment]
Hello @support-fennecx !

I've finally figure out what was happening, and luckily is not a plugin issue, just a bad code case.
For some reason, in some android xiaomi devices and Gboard keyboard, if you call `_inputTextField.ManualSelect();` when `_inputTextField.Selected== true`, it closes the keyboard and then it reopens again. 

I had a callback when the emoji button was pressed and was re-selecting the already selected input field, so just adding a IsSelected check fixed the issue.

Thanks for the support, you can close this if you want
Alberto
