### ISSUE TITLE
New autofilltypes for ios

### ISSUE THREAD

**Issue by tuxxmuxx** [support-fennecx/advancedinputfield2#23]
Hi, it would be nice if you could add the following autofill types.
name: UITextContentType
givenName: UITextContentType
middleName: UITextContentType
familyName: UITextContentType
location: UITextContentType
fullStreetAddress: UITextContentType
streetAddressLine1: UITextContentType
streetAddressLine2: UITextContentType
addressCity: UITextContentType
addressState: UITextContentType
addressCityAndState: UITextContentType
countryName: UITextContentType
postalCode: UITextContentType
telephoneNumber: UITextContentType

**Comment by support-fennecx** [comment]
Fixed in 2.0.6
