### ISSUE TITLE
Check why "Arabic Support for Unity" is working for version 1 of the plugin, but not version 2 of the plugin

### ISSUE THREAD

**Issue by support-fennecx** [support-fennecx/advancedinputfield2#26]
**Describe the bug**
Using "Arabic Support for Unity" plugin in combination with LiveDecorationFilters doesn't seem to work.
(Also see: https://forum.unity.com/threads/advanced-input-field-2.1028128/page-2)

**Expected behavior**
Should work the same as with version 1 of the plugin

**Environment**
 - OS: All
 - Version of the plugin 2.0.6

**Comment by OrionDev23** [comment]
Anything new about this ?

**Comment by OrionDev23** [comment]
Hello, yes it was me.
Just tested The 2nd version it seems to be working the same now for AIF2 as it did in AIF1, it was not working at all before, the carret position was messy and letters were not apearing at all,  so there is a progress, i can at least use the 2nd version now which is a great thing considering all the bug fixes and additions.

Still the behaviour is wrong, i'm making a multilanguage app, so i can't process the carret position without having to mess stuff, or test if what i'm currently typing is in arabic or not.

in arabic, the carret shoud be at the start (position 0) when writing while it's at the end for non-rtl languages.

There is also the problem with editing text, when you add an arabic letter , let's say from the second character, it should be added right after it, but it doesn't, it adds it at the 3rd position from the start, like it's inverted.

example : 

lets take this sentence : 
هدا مجر مثال
i want to add "د" after "ر" so it should be :
هدا مجرد مثال
But what we get is using this is :
هدا مدجر مثال

Do i just have to thing of a live decoration filter that adapts to the letters typed ? is it even possible ? if current word the carret if after is an arabic word the add the letter before, else after, something like that

**Comment by support-fennecx** [comment]
It might be easier to do with a LiveProcessingFilter in version 2 of the plugin. Such a filter can act as a main in the middle between the native inputfield and the inputfield in Unity and can compare previous and current text & selection states. See Documentation file for more info.

I will close this issue, because this issue covered a difference in behaviour between version 1 and 2  of the plugin.
