### ISSUE TITLE
On Android, auto completing a word that has been typed incorrectly does not fix the spelling of the word (when using emoji support)

### ISSUE THREAD

**Issue by Yi-GPS** [support-fennecx/advancedinputfield2#27]
**Describe the bug**
On Android, when a user types a partial word incorrectly, for example "advans", and choose the correctly spelling from the list fo suggested words provided by the keyboard, for example "advance", the resulting word still contains the typo. In this case here, the result will be "advanse".

**To Reproduce**
1. Build an Android apk with the AdvancedInputField_TextMeshPro_Text prefab that comes with the package. 
2. On the phone click on the input field
3. Type in something with incorrect spelling
4. Select any word from the suggested list by the keyboard
5. Observe the result

**Expected behavior**
The suggested word should replace the partially typed word, be it contains typo or not

**Screenshots**
![Screenshot_20210406-130357](https://user-images.githubusercontent.com/58192080/113786935-fca53380-96ee-11eb-8ef2-001fed2b153c.png)
![Screenshot_20210406-130409](https://user-images.githubusercontent.com/58192080/113786942-0038ba80-96ef-11eb-9d48-bca6c8287207.png)

**Environment**
 - OS: Android Version 11, Pixel 4 with Gboard
 - Version of the plugin: 2.0.7
 - Version of TextMeshPro: 2.1.1

**Comment by support-fennecx** [comment]
Seems to be caused by enabling emoji/rich text support
