### ISSUE TITLE
IOS - Keyboard height events not triggered by Advanced Input 2 but are triggered by normal TMP/regular input fields and work for Adv Input after

### ISSUE THREAD

**Issue by ROBYER1** [support-fennecx/advancedinputfield2#32]
**Describe the bug**
When using your advanced input field 2 plugin input fields in our apps, we have been relying on a callback for keyboard height from unisoftwarekeyboardarea plugin package here https://github.com/baba-s/UniSoftwareKeyboardArea
I have noticed that your input fields do not register the keyboard height on first press and they do not manage to register keyboard height until I have selected a normal TMP or generic Unity UI Input field.

I have made a quick simple repro project for you and also attached a video where I use the autofill form sample you have, I select username, password, TMP input field, normal unity UI input field in order and you can see the advanced input fields at the top do not activate the keyboard height which is shown by the green square. Once I have selected the tmp input field and the regular unity UI input field, keyboard height is working and even works for your fields.

I am not sure what is causing this behaviour, is it a bug or are we doing something wrong here?

**To Reproduce**

Repro project link! - https://drive.google.com/file/d/166pIjKVt1toW42_poF3LTwzxBoBr1QvQ/view?usp=sharing

1. Open the repro project in Unity 2020.3.0f1 build target IOS (not tested this on android yet but worth doing if you can)
2. Build and run scene> Keyboardheightbug
3. Run on ipad or iphone, first select one of your advanced input field 2 input fields at the top screen.
4. See that the green square in the UI does not match keyboard height
5. Select the TMP input field below or the normal unity input field below that - see that the green square for keyboard height now works
6. Select your advanced input field 2 input fields at the top screen again and see that now keyboard height is registering
7. Keyboard height doesn't register unless you click on a TMP input field or a Unity regular input field first for some reason?

**Expected behavior**
Keyboard height events should be triggered by Advanced input field v2 input fields always 

**Video Repro

https://user-images.githubusercontent.com/10745594/114919707-7db3a780-9e20-11eb-8ad3-b1a72cab7e49.MP4

**

**Environment**
 - OS: IOS 14.4
 - Advanced Input Field v2 version 2.0.8
 -TMP version 3.0.1
-Using Unity 2020.3.0f1
-Keyboard height using unisoftwarekeyboardarea : https://github.com/baba-s/UniSoftwareKeyboardArea

**Comment by support-fennecx** [comment]
Can't really say why this plugin doesn't work, might be because the AdvancedInputField plugin has it's own native bindings. 
The AdvancedInputField plugin itself already provides an event when keyboard height changes.
To register a listener to this event: NativeKeyboardManager.AddKeyboardHeightChangedListener().

Also, view the FAQ section of the Documentation file for more info.

**Comment by ROBYER1** [comment]
Thanks I'll try out using that then, was hoping you would know more than I did there!
