### ISSUE TITLE
Caret on inputfield is affected by worldspace position of the canvas on a screenspace canvas

### ISSUE THREAD

**Issue by ROBYER1** [support-fennecx/advancedinputfield2#35]
**Describe the bug**
When using the input field from your examples, on a screenspace canvas in our AR app where the Gyro/AR Foundation is moving the camera around in the scene, the input caret on your input fields' position is affected by the rotation of the canvas when it appears, making it appear broken.

I can share a video but this is very easy to reproduce - just use the AR Foundation samples and put a screenspace canvas in a scene with the AR Camera as it's target cam, add your advanced input field into the canvas and tap on/off the input field while moving the cam around in the build.

In this example gif, I am using AR Sim in the Unity editor to move the camera around AR to reproduce in the editor and you can see the caret gets fudged when the camera is moved.

**To Reproduce**
Use the AR Foundation samples and put a screenspace canvas in a scene with the AR Camera as it's target cam, add your advanced input field into the canvas and tap on/off the input field while moving the cam around in the build.

**Expected behavior**
Caret should be positioned in the local space of the canvas using localposition

**Screenshots**
![carot](https://user-images.githubusercontent.com/10745594/116782204-ae7e1880-aa7f-11eb-8f3f-3f4b9e380bfe.gif)

**Environment**
 - OS: IOS/Android/Unity Editoe with AR Simulation
 - Version of the plugin  2.0.9
 - Unity 2020.3.5f1

**Comment by support-fennecx** [comment]
Seems like the default rotation of the caret gets set to the world rotation of the Canvas when focusing a inputfield (even if the camera itself is already rotated).

So to fix it, I've explicitly set to local rotation to Quaternion.identity when initializing/updating the anchors.
Attached are the files I've changed
[AR Rotation fix.zip](https://github.com/support-fennecx/advancedinputfield2/files/6411128/AR.Rotation.fix.zip)

**Comment by ROBYER1** [comment]
> Seems like the default rotation of the caret gets set to the world rotation of the Canvas when focusing a inputfield (even if the camera itself is already rotated).
> 
> So to fix it, I've explicitly set to local rotation to Quaternion.identity when initializing/updating the anchors.
> Attached are the files I've changed
> [AR Rotation fix.zip](https://github.com/support-fennecx/advancedinputfield2/files/6411128/AR.Rotation.fix.zip)

Thankyou so much for the quick response and the hotfix, this will solve a load of issues in our AR app using your input fields as I was wondering why the testing feedback always mentioned the carets were dodgy but I never noticed it in editor!

Will this fix be merged into the next release also?
Thanks again and have a great weekend
