### ISSUE TITLE
Apple rejection of app due to 'password input field filling out email field + stuck carot'

### ISSUE THREAD

**Issue by ROBYER1** [support-fennecx/advancedinputfield2#36]
**Describe the bug**
This is in a production app that has gone through QA testing with us (10 staff members) and the client (another 10 members and their live users). The input fields in our login screen have always worked fine nobody has had issues and they are a straight 1-1 rip from the Form Example scene in your asset.

Today Apple rejected our app update (even though it passed review a good 5+ times before) due to apparently having the password input field filling out the username input field on our login screen.

To be clear we cannot reproduce this ourselves we have had 20+ people look at it and we have reached back out to apple to ask if they have any more information on how they managed to do this, I would like to know if you have any advice or have seen this issue before?

**To Reproduce**

I have attached the exact scene we find this issue happens in (according to Apple)
https://drive.google.com/file/d/1Nhx_9y7yaVaU8tl45gmQzh3FA3UtIU6X/view?usp=sharing
You can download this package, import Advanced input field into a project then import it, Scenes> Test> DodgyLoginInputField.scene

1. According to apple - delete and reinstall your app (use the test example scene forms)
2. Use the login fields, apparently when selecting the password field it still types into the username/email field?!

**Screenshots**
![attachment Screenshot-0701-160643](https://user-images.githubusercontent.com/10745594/124248243-8e6be380-db1a-11eb-961e-f657379c4174.png)

**Environment**
 - OS: iOS 14.6 Iphone + Ipad (apparently)
 - Version of the plugin 2.0.9
 - Unity Version 2020.3.6f1
 - Version of TextMeshPro 3.0.6

**Comment by support-fennecx** [comment]
Couldn't reproduce it myself using your scene. Didn't get any other reports about this issue either.
I know Apple review can be weird sometimes. Their testing environment is not always 100% the same as the tools they give the developers for testing. From the screenshot I guess it has an internal error somewhere, because there are 2 carets, but only 1 inputfield can be focused at a time (when using Unity UI EventSystem).
You can try asking for a log of their test device and/or update the plugin to latest version and submit a new build to Apple.

**Comment by ROBYER1** [comment]
You're right on with that, one of our testers actually managed to repro it here - they were using a magic ipad keyboard with their Ipad - I can get the full spec but what was happening was the magic keyboard had a field selected but couldn't type, while the touchscreen would allow the user to select another field so two carets appeared but they couldn't type.

We tested this our end with a different ipad keyboard (non-magic) and it typed into the fields just fine. Sounds like an IOS hardware keyboard specific bug.

Interestingly, we replied to Apple just saying "we can't repro this here, what did you do" and they didn't reply but just approved the app for distribution. Really really weird.

**Comment by support-fennecx** [comment]
I did fix a bluetooth keyboard issue recently that occurred only when the bluetooth keyboard was already connected when booting the app, so maybe that's the actual problem. Anyways, that fix be included in next release of the plugin.

Offtopic: I actually had a similar experience with Apple once with "in app purchase" functionality being rejected multiple times, but eventually got approved without changing anything when asking for more details. Apple can be a bit random :D
