### ISSUE TITLE
Autofill with native password managers on Android & iOS

### ISSUE THREAD

**Issue by support-fennecx** [support-fennecx/advancedinputfield2#8]
**Is your feature request related to a problem? Please describe.**
Add support for native password managers of Android & iOS.

**Describe the solution you'd like**
Allow adding and accessing credentials from the native password managers

**Comment by support-fennecx** [comment]
Fixed in 2.0.6

**Comment by kjyv** [comment]
This is working for Android most of the time (not all phones where I tried it) but never shows anything about saving or reading passwords on iOS - is this something we're doing wrong?
